#scenery constants
BLOCK_WIDTH = 71
BLOCK_HEIGHT = 50
BLOCK_HEIGHT_REAL = 61
BLOCK_Y_OVERLAP = BLOCK_HEIGHT_REAL - BLOCK_HEIGHT

NUM_BLOCKS = 9

X_OFFSET = 50
X_BORDER = X_OFFSET + NUM_BLOCKS * BLOCK_WIDTH

Y_OFFSET = 90
Y_BORDER = Y_OFFSET + NUM_BLOCKS * BLOCK_HEIGHT

#mouse event constants
LEFT = 1
RIGHT = 3
WHEEL_UP=4
WHEEL_DOWN=5

# cloud constants
MIN_TIME = 1000
MAX_TIME = 4000
WIND_SPEED = 0.00001